# Generated by Django 2.2.7 on 2022-02-10 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='is_solution',
        ),
        migrations.AddField(
            model_name='correctanswer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Questions'),
            preserve_default=False,
        ),
    ]
