# Generated by Django 2.2.7 on 2022-02-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='proints',
            field=models.IntegerField(),
        ),
    ]
